shorty/urls.py
from django.conf.urls import url, include

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('url_shortener.urls')),
]

url_shortener/urls.py
import os

from django.conf import settings
from django.conf.urls import url

from . import views

app_name = 'url_shortener'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<alias>[a-zA-Z0-9-_]+)$', views.redirect, name='alias'),
    url(r'^(?P<alias>[a-zA-Z0-9-_]+)(?P<extra>/.*)$', views.redirect, name='alias'),
    url(r'^(?P<alias>[a-zA-Z0-9-_]+)\+$', views.preview, name='preview'),
    url(r'^~analytics/$', views.analytics, name='analytics'),
]

# For Heroku
if 'DYNO' in os.environ:
    urlpatterns += [
        url(r'^~static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    ]

url_shortener/models.py
from urllib.parse import urlparse

from django.db import models
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator


class Link(models.Model):
    url = models.URLField(max_length=2083)
    alias = models.CharField(max_length=255, unique=True, validators=[
        RegexValidator(
            regex=r'^[a-z0-9-_]+$',
            code='invalid_alias',
            message='Alias can only contain lowercase alphabets, numerals, underscores and hyphens',
        ),
    ])
    clicks_count = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{0} -> {1}'.format(self.alias, self.url)

    def get_long_url_truncated(self, max_length=30, remove_schema=True):
        truncated_url = self.url
        if remove_schema:
            parsed_url = urlparse(truncated_url)
            scheme = parsed_url.scheme
            truncated_url = truncated_url[len(scheme)+3:]
            if parsed_url.path == '/' and not parsed_url.fragment and not parsed_url.query:
                truncated_url = truncated_url[:-1]
        if len(truncated_url) > max_length:
            truncated_url = truncated_url[:max_length] + '...'
        return truncated_url

    def get_date_created(self):
        return str(self.date_created)

    def get_date_created_human_friendly(self):
        return self.date_created.strftime('%Y %b %d, %I:%M %p')

    def get_alias_path(self):
        return reverse('url_shortener:alias', args=(self.alias,))

    def get_preview_path(self):
        return reverse('url_shortener:preview', args=(self.alias,))

url_shortener/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator

from .models import Link

_alias = Link._meta.get_field('alias')
_url = Link._meta.get_field('url')


class URLShortenerForm(forms.Form):

    alias = forms.CharField(
        max_length=_alias.max_length,
        required=False,
        help_text=_("An optional alias you want to generate. "
                    "One will be chosen automatically if you don't enter one."),
        label=_('Alias (optional)'),
        validators=[RegexValidator(
            regex=r'^[a-zA-Z0-9-_]+$',
            code='invalid_alias',
            message='Alias can only contain alphabets, numerals, underscores and hyphens',
        )]
    )

    url = forms.URLField(
        max_length=_url.max_length,
        required=True,
        help_text=_("The URL you want to shorten."),
        label=_('Long URL to shorten'),
        widget=forms.URLInput(
            attrs={'placeholder': 'http://www.example.com/index.php?id=321&redirect=1&guest&coords=1,1,3,32,53',
                   'required': 'true'},
        ),
    )

url_shortener/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import (HttpResponseRedirect,
                         Http404,
                         HttpResponsePermanentRedirect)

from .misc import (hash_encode,
                   get_absolute_short_url)
from .forms import URLShortenerForm
from .models import Link


def index(request):
    if request.method == 'POST':
        form = URLShortenerForm(request.POST)
        if form.is_valid():
            original_alias = form.cleaned_data['alias']
            alias = original_alias.lower()
            url = form.cleaned_data['url']
            new_link = Link(url=url)
            try:
                latest_link = Link.objects.latest('id')
                if Link.objects.filter(alias__exact=alias):
                    # handle alias conflict
                    new_link.alias = hash_encode(latest_link.id+1)
                    messages.add_message(request, messages.INFO,
                                         'Short URL {} already exists so a new short URL was created.'
                                         .format(get_absolute_short_url(request, original_alias)))
                    original_alias = new_link.alias
                else:
                    new_link.alias = alias or hash_encode(latest_link.id+1)
            except Link.DoesNotExist:
                new_link.alias = alias or hash_encode(1)
            new_link.save()
            return HttpResponseRedirect(reverse('url_shortener:preview', args=(original_alias or new_link.alias,)))
    else:
        form = URLShortenerForm()
    return render(request, 'url_shortener/index.html', {
        'form': form,
        'absolute_index_url': get_absolute_short_url(request, ''),
    })


def preview(request, alias):
    link = get_object_or_404(Link, alias__iexact=alias)
    return render(request, 'url_shortener/preview.html', {
        'alias': alias,
        'absolute_short_url': get_absolute_short_url(request, alias, remove_schema=False),
        'url': link.url,
    })


def redirect(request, alias, extra=''):
    link = get_object_or_404(Link, alias__iexact=alias)
    link.clicks_count += 1
    link.save()
    return HttpResponsePermanentRedirect(link.url + extra)


def analytics(request):
    links = list(Link.objects.all().order_by('-id'))
    if not links:
        return render(request, 'url_shortener/analytics.html')

    lim = 10
    try:
        page = int(request.GET['page'])
        if page <= 0:
            raise Http404("?page= parameter must be a valid positive integer")
    except KeyError:
        page = 1
    except ValueError:
        raise Http404('?page= parameter must be a valid positive integer')

    max_pages = len(links) // lim + bool(len(links) % lim)
    if page > max_pages:
        raise Http404('page ({}) is greater than max_pages ({})'.format(page, max_pages))

    if page == max_pages:
        # just get the remaining last items
        curr_links = links[-(len(links) % lim):]
    else:
        start = (page-1) * lim
        end = (page) * lim
        curr_links = links[start:end]
    return render(request, 'url_shortener/analytics.html', {
        'links': curr_links,
        'page': page,
        'max_pages': max_pages,
        'count_pages': ''.join(['x' for i in range(max_pages)]),  # HACK
    })

templates/url_shortener/analytics.html
{% extends 'url_shortener/base.html' %}

{% block title %}Analytics - {{ title }}{% endblock %}

{% block analytics_nav %}active{% endblock %}

{% block local_nav %}
{% endblock %}

{% block content %}
{% if links %}
  <p>All short URLs and their click analytics is publicly available. Time is in UTC format.</p>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>Long URL</td>
        <td>Created</td>
        <td>Short URL</td>
        <td>Clicks</td>
      </tr>
    </thead>
    <tbody>
    {% for link in links %}
      <tr>
        <td><a href="{{ link.url }}">{{ link.get_long_url_truncated }}</a></td>
        <td>{{ link.get_date_created_human_friendly }}</td>
        <td><a href="{{ link.get_preview_path }}">{{ link.alias }}</a></td>
        <td>{{ link.clicks_count }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <nav>
    <ul class="pagination">
      {# Left #}
      <li{% if page == 1 %} class="disabled"{% endif %}>
        <a{% if page != 1 %} href='?page={{ page|add:"-1" }}'{% endif %} aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>

      {# The list item #}
      {% for i in count_pages %}
        <li{% if forloop.counter == page %} class="active"{% endif %}>
          <a href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
      {% endfor %}

      {# Right #}
      <li{% if page == max_pages %} class="disabled"{% endif %}>
        <a{% if page != max_pages %} href='?page={{ page|add:"1" }}'{% endif %} aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
{% else %}
  <h1>No short URLs exist yet.</h1>
  <p>Zero URLs have been shortened as of now.</p>
  <p><a class="btn btn-primary" href="{% url 'url_shortener:index' %}" role="button">Shorten some URLs!</a></p>
{% endif %}
{% endblock %}

templates/url_shortener/base.html
{% with "URL Shortener" as title %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ title }}{% endblock %}</title>
  <!-- Bootstrap CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  {# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous"> #}
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <link rel="stylesheet" href="{% static 'url_shortener/main.css' %}" />
</head>
<body>
  <div id="wrapper">
    <div class="jumbotron" id="banner" style="padding-bottom: 0;">
      <div class="container">
        <h1><a href="{% url 'url_shortener:index' %}">URL Shortener</a></h1>
        <p>Shorten your long URLs and share them with your friends!</p>
        <ul class="nav nav-tabs" style="border: 0;">
          <li role="presentation" class="{% block index_nav %}{% endblock %}"><a href="{% url 'url_shortener:index' %}">Home</a></li>
          <li role="presentation" class="{% block analytics_nav %}{% endblock %}"><a href="{% url 'url_shortener:analytics' %}">Analytics</a></li>
          {% block navextra %}{% endblock %}
        </ul>
      </div>
    </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <div id="push"></div>
  </div>
  <div id="footer">
    <div class="container">
      <p class="muted credit">
        Copyright &copy; 2016 Sumit Chahal.
        Source code available on <a href="https://github.com/smtchahal/url-shortener">GitHub</a>.
      </p>
    </div>
  </div>
  <!-- jQuery CDN -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- jQuery local fallback -->
  <script>window.jQuery || document.write('<script src="{% static 'jquery-1.11.3/jquery.min.js' %}"><\/script>')</script>
  <!-- Bootstrap JS CDN -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <!-- Bootstrap JS local fallback -->
  <script>if(typeof($.fn.modal) == 'undefined') {document.write('<script src="{% static 'bootstrap-3.3.6/js/bootstrap.min.js' %}"><\/script>')}</script>
  <!-- Bootstrap CSS local fallback -->
  <script>
    $(document).ready(function() {
      var bodyColor = $('body').css('color');
      if (bodyColor != 'rgb(51, 51, 51)') {
        $('head').prepend('<link rel="stylesheet" href="{% static 'bootstrap-3.3.6/css/bootstrap.min.css' %}" />');
      }
    });
  </script>
  {% block bodyextra %}{% endblock %}
</body>
</html>
{% endwith %}

templates/url_shortener/index.html
{% extends 'url_shortener/base.html' %}
{% load widget_tweaks %}

{% block index_nav %}active{% endblock %}

{% block content %}
<form role="form" action="{% url 'url_shortener:index' %}" method="post">
  {% csrf_token %}

  {% for error in form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error</span>
    {{ error }}
  </div>
  {% endfor %}

  <div class="form-group">
    {% for error in form.url.errors %}
    <div class="alert alert-danger" role="alert">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error</span>
      {{ error }}
    </div>
    {% endfor %}
    <label for="{{ form.url.id_for_label }}">{{ form.url.label }}</label>
    <div class="input-group{% if form.url.errors %} has-error{% endif %}">
      {{ form.url|add_class:"form-control input-lg"|attr:"aria-describedby:url-addon" }}
      <span class="input-group-btn">
        <button class="btn btn-primary btn-lg" type="submit">Go!</button>
      </span>
    </div>
  </div>

  <!--
  <div class="form-group">
    <input class="btn btn-primary center-block" type="submit" value="Make it short!" />
  </div> -->

  <div class="form-group">
    {% for error in form.alias.errors %}
    <div class="alert alert-danger" role="alert">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error</span>
      {{ error }}
    </div>
    {% endfor %}
    <label for="{{ form.alias.id_for_label }}">{{ form.alias.label }}</label>
    <div class="input-group{% if form.alias.errors %} has-error{% endif %}">
      <span class="input-group-addon" id="alias-addon">{{ absolute_index_url }}</span>
      {{ form.alias|add_class:"form-control"|attr:"aria-describedby:alias-addon" }}
    </div>
  </div>

</form>
{% endblock %}

templates/url_shortener/preview.html
{% extends 'url_shortener/base.html' %}

{% block title %}Preview - {{ title }}{% endblock %}

{% block navextra %}
<li role="presentation" class="active"><a href="{{ request.get_full_path }}">Preview</a></li>
{% endblock %}

{% block content %}
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-info" role="info">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
      <span class="sr-only">Information</span>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
<p><input type="text" id="shortened-url" readonly class="form-control input-lg" value="{{ absolute_short_url }}" /></p>
<p>This short URL redirects to:</p>
<div id="url" class="lead">{{ url }}</div>
<div class="btn-toolbar" role="toolbar" aria-label="buttons-toolbar">
  <a class="btn btn-primary" href="{{ url }}">Proceed to this site</a>
  <a class="btn btn-success" href="{% url 'url_shortener:index' %}">Shorten another URL</a>
</div>
{% endblock %}

{% block bodyextra %}
<script>
$('#shortened-url').focus().select().click(function() {
  $(this).select();
});
</script>
{% endblock %}